web/config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :notes
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "books#index"
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: {maximum: 255, too_long: "%{count} caracteres es el maximo permitido"}

  def export_pdf
    pdf = Prawn::Document.new
    pdf.text "Libro: #{name}"
    pdf.move_down 20
    pdf.text "Notas:"
    pdf.move_down 20
    notes.each do |note|
      pdf.move_down 20
      pdf.text "Titulo: #{note.title}"
      pdf.move_down 20
      pdf.text "Contenido:"
      pdf.move_down 20
      pdf.styled_text note.body.to_s
      pdf.move_down 20
      pdf.text "----------------------------------------------"
    end
    pdf
  end

end

web/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :title, presence: true, uniqueness: true, length: {maximum: 255, too_long: "%{count} caracteres es el maximo permitido"}
  has_rich_text :body

  def export_pdf
    pdf = Prawn::Document.new
    pdf.text "Titulo: #{title}"
    pdf.move_down 20
    pdf.text "Contenido:"
    pdf.move_down 20
    pdf.styled_text body.to_s
    pdf
  end
end

web/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  after_create :create_global_book

  def create_global_book
    books.create(name: "Global")
  end

end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

web/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    @books = current_user.books.paginate(page: params[:page], per_page: 10)
  end

  # GET /books/1
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = @book.export_pdf
        send_data pdf.render, filename: "export_#{@book.name}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = current_user.books.new(book_params)

    if @book.save
      redirect_to books_path, notice: 'Libro creado exitosamente'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Libro modificado exitosamente'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Libro eliminado'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = current_user.books.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name)
    end
end

web/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :export , :destroy]
  before_action :set_book, except:  [:destroy, :export]

  # GET /notes
  def index
    @notes = @book.notes.paginate(page: params[:page], per_page: 10)
  end

  # GET /notes/1
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = @note.export_pdf
        send_data pdf.render, filename: "export_#{@note.title}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /notes/new
  def new
    @books = Book.all
    @note = @book.notes.new
  end

  # GET /notes/1/edit
  def edit
    @books = Book.all
  end

  # POST /notes
  def create
    @books = Book.all
    @note = @book.notes.new(note_params)

    if @note.save
      redirect_to book_notes_path(@book), notice: 'Note was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /notes/1
  def update
    if @note.update(note_params)
      redirect_to book_note_path(@book, @note), notice: 'Note was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /notes/1
  def destroy
    @note.destroy
    redirect_to book_notes_url, notice: 'Note was successfully destroyed.'
  end

  private
    def set_book
      @book = params[:book_id].present? ? (current_user.books.find(params[:book_id])) : (current_user.books.find_by(name: "Global"))
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_note
      set_book
      @note = @book.notes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :body, :book_id, :user_id).merge(user_id: current_user.id)
    end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

web/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre_de_libro %>
    <%= form.text_field :name, class: "form-control", style: "max-width: 250px;", maxlength: 255 %>
  </div>

  <div class="actions">
    <%= form.submit "Crear libro", class: 'btn btn-success' %>
    <%= link_to 'Volver', books_path, class: "btn btn-danger" %>
  </div>
<% end %>

web/app/views/books/edit.html.erb
<h1>Editar libro</h1>

<%= render 'form', book: @book %>

web/app/views/books/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Listado de libros</th>
      <th scope="col">Cantidad de notas</th>
      <th scope="col" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.notes.count %></td>
        <td><%= link_to 'Acceder a Notas', book_notes_path(book) %></td>
        <td><%= link_to_if((book.name != "Global"), 'Editar nombre de libro', edit_book_path(book)) %></td>
        <td><%= link_to 'Exportar', book_path(book, format: "pdf"), target: "_blank" %></td>
        <td><%= link_to_if((book.name != "Global"), "Eliminar Libro", book, method: :delete) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<div class="apple_pagination">
    <%= will_paginate @books, :container => false %>
</div>

<br>
<%= link_to 'Nueva nota', new_book_note_path(current_user.books.find_by(name: "Global")), class: "btn btn-success" %>
<%= link_to 'Nuevo libro', new_book_path, class: "btn btn-success" %>

web/app/views/books/new.html.erb
<h1>Creacion de libro</h1>

<%= render 'form', book: @book %>

web/app/views/books/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Cantidad de notas:</strong>
  <%= @book.notes.count %>
</p>

<%= link_to 'Back', books_path, class: "btn btn-danger" %>

web/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-top: 10px;">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Bienvenido, <%= current_user.email %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TTPS-Ruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if user_signed_in? %>
  <%= render 'layouts/navbar' %>
  <% end %>

  <body class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

web/app/views/notes/_form.html.erb
<%= form_with(model: [@book, note]) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :libro %>
    <%= form.select :book_id, @books.all.pluck(:name, :id), {}, { class: "form-select" }  %>
  </div>

  <div class="field" style="margin-top: 20px;">
    <%= form.label :titulo %>
    <%= form.text_field :title, maxlength: 255, size: 20 %>
  </div>

  <div class="field" style="margin-top: 20px;">
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions" style="margin-top: 10px;">
    <%= form.submit "Guardar", class: 'btn btn-success', id: "button" %>
    <%= link_to 'Volver', book_notes_path(@book), class: "btn btn-danger" %>
  </div>
<% end %>

web/app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

web/app/views/notes/index.html.erb
<h1>Notas del libro "<%= @book.name %>"</h1>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">Titlulo</th>
      <th scope="col">Contenido</th>
      <th scope="col" colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><span class="truncate"><%= note.body.to_plain_text %></span></td>
        <td><%= link_to 'Abrir', book_note_path(@book, note) %></td>
        <td><%= link_to 'Editar', edit_book_note_path(@book, note) %></td>
        <td><%= link_to 'Exportar', book_note_path(@book, note, format: "pdf"), target: "_blank" %></td>
        <td><%= link_to 'Eliminar', book_note_path(@book, note), method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="apple_pagination">
    <%= will_paginate @notes, :container => false %>
</div>

<br>

<%= link_to 'Nueva nota', new_book_note_path(@book), class: "btn btn-success" %>
<%= link_to 'volver', books_path, class: "btn btn-danger"  %>

web/app/views/notes/new.html.erb
<h1>Crear nueva nota</h1>

<%= render 'form', note: @note %>

web/app/views/notes/show.html.erb
<p>
  <strong>Libro:</strong>
  <%= @note.book.name %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @note.body %>
</p>

<%= link_to 'Edit', edit_book_note_path(@book, @note), class: 'btn btn-success' %>
<%= link_to 'Back', book_notes_path(@book), class: 'btn btn-danger' %>

web/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

web/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>